Repository djpugh/fastapi_aad_auth, pull requests merged in 2020-12, with the labels that each got.

#28 User class documentation and improvements
  docs/source/advanced.rst
  docs/source/conf.py
  docs/source/config.rst
  docs/source/development.rst
  docs/source/index.rst
  docs/source/module/fastapi_aad_auth.auth.rst
  docs/source/module/fastapi_aad_auth.config.rst
  docs/source/module/fastapi_aad_auth.errors.rst
  docs/source/module/fastapi_aad_auth.oauth._base.rst
  docs/source/module/fastapi_aad_auth.oauth.aad.rst
  docs/source/module/fastapi_aad_auth.oauth.authenticators.rst
  docs/source/module/fastapi_aad_auth.oauth.authenticators.session.rst
  docs/source/module/fastapi_aad_auth.oauth.rst
  docs/source/module/fastapi_aad_auth.oauth.state.rst
  docs/source/module/fastapi_aad_auth.oauth.validators.rst
  docs/source/module/fastapi_aad_auth.oauth.validators.session.rst
  docs/source/module/fastapi_aad_auth.oauth.validators.token.rst
  docs/source/module/fastapi_aad_auth.ui.rst
  docs/source/usage.rst
  src/fastapi_aad_auth/config.py
  src/fastapi_aad_auth/oauth/__init__.py
  src/fastapi_aad_auth/oauth/aad.py
  src/fastapi_aad_auth/ui/__init__.py
Labels: automerge, feature

#29 Change User.roles and User.groups to optional
  src/fastapi_aad_auth/oauth/state.py
  src/fastapi_aad_auth/oauth/validators/token.py
Labels: bug

#31 Fixing PR Labelling on forks
  .github/pr-labeler.yaml
Labels: automerge, fix

#33 Feature/extensible templates
  docs/source/advanced.rst
  docs/source/module/fastapi_aad_auth.ui.base.html.rst
  docs/source/module/fastapi_aad_auth.ui.error.html.rst
  docs/source/module/fastapi_aad_auth.ui.jinja.rst
  docs/source/module/fastapi_aad_auth.ui.login.html.rst
  docs/source/module/fastapi_aad_auth.ui.rst
  docs/source/module/fastapi_aad_auth.ui.user.html.rst
  src/fastapi_aad_auth/auth.py
  src/fastapi_aad_auth/config.py
  src/fastapi_aad_auth/ui/__init__.py
  src/fastapi_aad_auth/ui/base.html
  src/fastapi_aad_auth/ui/error.html
  src/fastapi_aad_auth/ui/jinja.py
  src/fastapi_aad_auth/ui/login.html
  src/fastapi_aad_auth/ui/user.html
  src/fastapi_aad_auth/utilities/__init__.py
Labels: automerge, feature

#34 Fixing lint
  src/fastapi_aad_auth/ui/__init__.py
Labels: automerge, fix

#35 Updating templates to use module based pathing for easier inheritance
  src/fastapi_aad_auth/auth.py
  src/fastapi_aad_auth/ui/__init__.py
  src/fastapi_aad_auth/ui/error.html
  src/fastapi_aad_auth/ui/login.html
  src/fastapi_aad_auth/ui/user.html
Labels: automerge, fix

#36 Adding more blocks to templates
  src/fastapi_aad_auth/ui/error.html
  src/fastapi_aad_auth/ui/login.html
  src/fastapi_aad_auth/ui/user.html
Labels: automerge, feature

#37 Fixing for auth not enabled
  src/fastapi_aad_auth/_base/backend.py
  src/fastapi_aad_auth/auth.py
  src/fastapi_aad_auth/config.py
  src/fastapi_aad_auth/ui/__init__.py
Labels: automerge

#38 Fixing typo
  src/fastapi_aad_auth/auth.py
Labels: automerge, fix

#39 Adding cleaner handling for multiple providers
  src/fastapi_aad_auth/_base/backend.py
  src/fastapi_aad_auth/_base/validators/token.py
  src/fastapi_aad_auth/errors.py
  src/fastapi_aad_auth/utilities/__init__.py
Labels: automerge

#41 Adding scopes handling/inclusion in tickets
  docs/source/advanced.rst
  src/fastapi_aad_auth/_base/authenticators/session.py
  src/fastapi_aad_auth/_base/state.py
  src/fastapi_aad_auth/_base/validators/session.py
  src/fastapi_aad_auth/auth.py
  src/fastapi_aad_auth/config.py
  src/fastapi_aad_auth/errors.py
  src/fastapi_aad_auth/providers/aad.py
  src/fastapi_aad_auth/ui/__init__.py
  src/fastapi_aad_auth/ui/error.html
  src/fastapi_aad_auth/utilities/urls.py
Labels: automerge, fix

#43 Handling None in redirect
  src/fastapi_aad_auth/_base/validators/session.py
Labels: automerge, fix

#44 Handling blank values in expected routes
  src/fastapi_aad_auth/_base/validators/session.py
  src/fastapi_aad_auth/config.py
Labels: automerge, fix

#46 Redirect from /me token request if auth required
  src/fastapi_aad_auth/_base/authenticators/session.py
  src/fastapi_aad_auth/_base/provider.py
  src/fastapi_aad_auth/ui/__init__.py
  src/fastapi_aad_auth/ui/user.html
  src/fastapi_aad_auth/utilities/urls.py
Labels: automerge, feature

#45 Add inheritable classes for e.g. Users and Configs
  src/fastapi_aad_auth/_base/provider.py
  src/fastapi_aad_auth/_base/state.py
  src/fastapi_aad_auth/config.py
  src/fastapi_aad_auth/providers/aad.py
  src/fastapi_aad_auth/utilities/__init__.py
  src/fastapi_aad_auth/utilities/basemodel.py
Labels: automerge, feature

#47 Fixing user class reload with tests
  src/fastapi_aad_auth/_base/state.py
  tests/unit/test_auth_state.py
Labels: automerge, fix

#48 Fixing auth provider without authenticator error
  src/fastapi_aad_auth/ui/__init__.py
Labels: automerge, fix

#49 Adding login_ui safe filter
  src/fastapi_aad_auth/ui/__init__.py
  src/fastapi_aad_auth/ui/login.html
Labels: automerge, fix

#50 Adding redirect uri logging
  src/fastapi_aad_auth/providers/aad.py
Labels: automerge
